fieldLayouts:
  96b50897-5f3a-4129-a876-34f9f77d8362:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 063917aa-0ac7-42be-85b3-ab29d6fc6494 # Position
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b4c0f8da-526c-431b-8cd3-87efc0dc78e0 # Team
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c43092c0-9b16-4bf6-bff0-134991c0e7ce # Location
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 6c60f362-9ffc-4acd-80e9-92cd16c65c3d # Expertise
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Main
        sortOrder: 1
      -
        elements:
          -
            fieldUid: a3c8bb83-4adf-4835-82db-a806831d245d # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: ddc03f1b-ce2f-4e1e-9470-492bb69f785a # Excerpt
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: bc45b907-cf21-4be7-8773-8dbe9e1bafcf # Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: e86890fe-2eb2-4c65-a61f-6ed600052d1c # Qualifications
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 479865f5-a696-401e-a2d5-59e13cfc028d # Quote
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Information
        sortOrder: 2
      -
        elements:
          -
            fieldUid: aebeca5b-5196-44a5-b8fb-d551dbb79d3c # Phone
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 1deb9945-3522-4d09-be51-2a18c2bc86e4 # LinkedIn
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: ad3c872a-8334-4a4a-b942-667cb670f605 # Email
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 4f8408f8-b7f1-4edc-a7cd-3a772b4f227e # Alternate Contact Name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 02478477-f7ca-4a5a-811a-bfe36d39612c # Alternate Contact Position
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 1623d538-e579-4a44-93c6-8b8eedde1620 # Alternate Contact Email
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 853acb84-7077-4eb4-8476-531eb77890db # Alternate Contact Phone
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Contacts
        sortOrder: 3
      -
        elements:
          -
            fieldUid: 3e2ca1eb-5666-49a9-9337-3996db17444b # Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 54e8019e-8701-43a9-92d1-92715c5750f0 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Hero
        sortOrder: 4
      -
        elements:
          -
            fieldUid: f83ca24c-2b75-4662-bf70-e596fb2a6143 # SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: SEO
        sortOrder: 5
      -
        elements:
          -
            fieldUid: 33e21064-b628-40c7-b468-ea1796d59834 # Blocks
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Blocks
        sortOrder: 6
handle: default
hasTitleField: true
name: Default
section: d81682b5-9246-4268-8cda-45428b5c2eb3 # People
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
