fieldLayouts:
  c1197e9a-3830-4b8f-b906-addc94e8db3a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: e4c62493-0e1d-45f2-80aa-bc5edfc38ba8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: fbddf8cd-aec2-4c00-aea8-075e04dae8d8 # News Categories
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ac71299d-355e-4b44-b0dd-cafba1abb5f1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c2ab5aa8-a1e0-423f-8bdf-b5a2cdddc0d7 # Is News Article
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: afde2090-cf55-4530-b870-c9e8c6b7eb0b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 07cabf3d-4ebf-4c33-b3c7-2f97e9ce789b # Is Insight Article?
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9a2d28ec-2743-43ba-85b4-f057a06a8ed5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a3c8bb83-4adf-4835-82db-a806831d245d # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 400631de-e86d-4d97-b155-e05a17798611
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5c00c8db-d5d5-423e-88ad-929a70b96513 # Content
            instructions: null
            label: Summary
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4765fbd0-6bc8-4d98-8c76-224df05803f1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 33e21064-b628-40c7-b468-ea1796d59834 # Blocks
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cb370e88-c3f3-46ad-8da6-8aba25e8dddc
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ebee0638-8638-4443-887d-526789c92e71
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 3e2ca1eb-5666-49a9-9337-3996db17444b # Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d5d46a41-e260-4caa-8d48-c96406283ab9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 54e8019e-8701-43a9-92d1-92715c5750f0 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b44ffd94-5b1f-492e-8938-8595ab580c5d
            userCondition: null
            warning: null
            width: 100
        name: Hero
        uid: 69084ed7-3d7b-40ac-91e5-e3283cdf229d
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: f83ca24c-2b75-4662-bf70-e596fb2a6143 # SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: da5ba928-4a78-440d-9e9e-2441a2d8ee6b
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 16acd3a8-5f3d-41e8-b09c-be3896f93b7a
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: bdda9a00-f9cc-41c0-bf21-44a4cfa8927d # News Page
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
