defaultPlacement: end
fieldLayouts:
  2c2913bb-b94d-463d-852e-371a1c6c11c9:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: expertise
name: Expertise
siteSettings:
  b435198f-89d2-4c06-b0e1-e3d2dc874d2c: # Tavendale & Partners
    hasUrls: true
    template: _singles/people
    uriFormat: 'our-people/{slug}'
structure:
  maxLevels: 1
  uid: f494d4e1-a491-4e44-94a9-c6cba39c9cb8
