defaultPlacement: end
fieldLayouts:
  ee0ebdb1-1b48-4d80-9dc4-f7e4bb539f84:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: locations
name: Locations
siteSettings:
  b435198f-89d2-4c06-b0e1-e3d2dc874d2c: # Tavendale & Partners
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: 1
  uid: 21186a15-b75e-4cfe-8bd9-71814e54f2e0
