baseUrl: $PRIMARY_SITE_URL
enabled: true
handle: default
hasUrls: true
language: en-US
name: 'Tavendale & Partners'
primary: true
siteGroup: 6ef74d87-bf43-4cb6-9901-6e15a1efad4b # Tavendale & Partners
sortOrder: 1
