childBlocks:
  - accordionItem
conditions: null
description: ''
enabled: true
field: 33e21064-b628-40c7-b468-ea1796d59834 # Blocks
fieldLayouts:
  c94f7d10-5890-4e2d-9a71-21936aee3dfc:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 5c20a627-5111-454c-af25-51dd24681d70 # Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 78059bb7-cfc7-40c5-9cd2-95aebeba34dd
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ddc03f1b-ce2f-4e1e-9470-492bb69f785a # Excerpt
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ef1b6d94-96e5-426f-b1b6-32f4ccce3dfa
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: bc45b907-cf21-4be7-8773-8dbe9e1bafcf # Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4ea5d4e7-bb68-41fe-8070-ade7530d2c78
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4095fa84-00a3-4d80-af89-4b51ebedf570 # CTA Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 19fb3bf9-e010-4d6c-81f9-a68392522d40
            userCondition: null
            warning: null
            width: 100
        name: Main
        uid: 185c3bf2-910e-4b8b-839c-42b8113e0666
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 477046a3-12f5-4a73-82c4-d7e4fc8f9958 # Bottom Spacing
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5c861c8e-ceda-42f9-b2f1-3a8fdf027ada
            userCondition: null
            warning: null
            width: 100
        name: Spacing
        uid: 692cb497-8ef2-4623-aa12-9003b34741bf
        userCondition: null
group: null
groupChildBlockTypes: true
handle: accordionBlock
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Accordion block'
topLevel: true
