childBlocks: null
conditions: null
description: ''
enabled: true
field: 33e21064-b628-40c7-b468-ea1796d59834 # Blocks
fieldLayouts:
  d2f0b56a-26fa-49ea-aec3-6a2f4021e427:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 5c20a627-5111-454c-af25-51dd24681d70 # Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 887ad62b-b78a-48b3-b8d3-d1ca11c89555
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ddc03f1b-ce2f-4e1e-9470-492bb69f785a # Excerpt
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 907f3aa4-53b4-4031-aaf6-31f2d66dc579
            userCondition: null
            warning: null
            width: 100
        name: Main
        uid: 66619976-80b9-43f9-965e-f44489516c05
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 477046a3-12f5-4a73-82c4-d7e4fc8f9958 # Bottom Spacing
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fa88f5dc-b8bd-4471-88db-1f269c9731ed
            userCondition: null
            warning: null
            width: 100
        name: Spacing
        uid: ba9a77a0-3479-4c41-b629-ee5a6b943b65
        userCondition: null
group: null
groupChildBlockTypes: true
handle: careerOpportunities
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Career Opportunities'
topLevel: true
