childBlocks: null
field: 33e21064-b628-40c7-b468-ea1796d59834 # Blocks
fieldLayouts:
  da34f41a-e923-494b-b1b5-2521ff7646b6:
    tabs:
      -
        elements:
          -
            fieldUid: 5c20a627-5111-454c-af25-51dd24681d70 # Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: ddc03f1b-ce2f-4e1e-9470-492bb69f785a # Excerpt
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Main
        sortOrder: 1
group: null
handle: cell
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: Cell
topLevel: false
