childBlocks: null
field: 33e21064-b628-40c7-b468-ea1796d59834 # Blocks
fieldLayouts:
  b2e4c336-4c54-47f0-9595-d808fcfabc4d:
    tabs:
      -
        elements:
          -
            fieldUid: 5c20a627-5111-454c-af25-51dd24681d70 # Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: a3c8bb83-4adf-4835-82db-a806831d245d # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 5c00c8db-d5d5-423e-88ad-929a70b96513 # Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 4095fa84-00a3-4d80-af89-4b51ebedf570 # CTA Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Main
        sortOrder: 1
group: null
handle: column
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: Column
topLevel: false
