childBlocks:
  - cell
conditions: null
description: ''
enabled: true
field: 33e21064-b628-40c7-b468-ea1796d59834 # Blocks
fieldLayouts:
  8dfcafaa-31bd-4743-856a-ca51ee33d0c2:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 477046a3-12f5-4a73-82c4-d7e4fc8f9958 # Bottom Spacing
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b009e264-ec44-4f79-a2a8-5a1cb90e014b
            userCondition: null
            warning: null
            width: 100
        name: Spacing
        uid: 77896d9a-a77c-4b58-ae4f-010947dc35a9
        userCondition: null
group: null
groupChildBlockTypes: true
handle: contentGrid
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Content Grid'
topLevel: true
