childBlocks:
  - cell
field: 33e21064-b628-40c7-b468-ea1796d59834 # Blocks
fieldLayouts:
  078944ea-eceb-4eed-8681-66b01a30e5e2:
    tabs:
      -
        elements:
          -
            fieldUid: 477046a3-12f5-4a73-82c4-d7e4fc8f9958 # Bottom Spacing
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Spacing
        sortOrder: 1
group: null
handle: contentGrid
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: 'Content Grid'
topLevel: true
