childBlocks: null
conditions: null
description: ''
enabled: true
field: 33e21064-b628-40c7-b468-ea1796d59834 # Blocks
fieldLayouts:
  be68699c-6e2a-4b7d-85a3-18bd6a63816c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 5c20a627-5111-454c-af25-51dd24681d70 # Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dee95520-27e0-4bf0-8baf-301a375672a5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2ec68185-9783-4e5d-a1eb-70dc93f81993 # Background
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 67bbf9f0-7097-49e0-957a-17209d4b0a4a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4095fa84-00a3-4d80-af89-4b51ebedf570 # CTA Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 550ee6b8-812b-42e2-93e4-1cb347c909d1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: eeb92060-c786-42a9-bcfe-714a0bb08357 # Animation Primary Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ae4f4b92-d3e5-4e01-881c-5d971bdc9207
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 12c77a35-7a1b-4ae4-8ddb-d9b81eda22f7 # Animation Secondary Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f1509968-e046-4dd0-a096-8af402f7a27f
            userCondition: null
            warning: null
            width: 100
        name: Main
        uid: 9ee58a7a-d43e-4376-9efc-a4ff69089504
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 477046a3-12f5-4a73-82c4-d7e4fc8f9958 # Bottom Spacing
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 343b9f80-def0-4bb5-b367-171532847863
            userCondition: null
            warning: null
            width: 100
        name: Spacing
        uid: e03e9e8a-8b62-49af-ae3d-e285524543f7
        userCondition: null
group: null
groupChildBlockTypes: true
handle: ctaBlock
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: CTA
topLevel: true
