childBlocks:
  - instagramImage
conditions: null
description: ''
enabled: true
field: 33e21064-b628-40c7-b468-ea1796d59834 # Blocks
fieldLayouts:
  9c5a0f73-a60b-40b8-b730-94edc40cae4b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 5c20a627-5111-454c-af25-51dd24681d70 # Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 12498ff9-940e-42dd-bcca-26530a974dbb
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 043dff96-faf7-47d4-a319-43ad57ccfec5 # Hash Tag
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0b034a6a-32e8-4d54-a417-c1cab9bd8437
            userCondition: null
            warning: null
            width: 100
        name: Main
        uid: 28711ab4-7f37-48d9-866b-368382b4521a
        userCondition: null
group: null
groupChildBlockTypes: true
handle: instagram
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: Instagram
topLevel: true
