childBlocks: null
field: 33e21064-b628-40c7-b468-ea1796d59834 # Blocks
fieldLayouts:
  9beeb079-e3f4-4b88-80fd-53fb45535e1e:
    tabs:
      -
        elements:
          -
            fieldUid: a3c8bb83-4adf-4835-82db-a806831d245d # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 4095fa84-00a3-4d80-af89-4b51ebedf570 # CTA Link
            instructions: ''
            label: Link
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Main
        sortOrder: 1
group: null
handle: instagramImage
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: 'Instagram Image'
topLevel: false
