childBlocks:
  - instagramImage
field: 33e21064-b628-40c7-b468-ea1796d59834 # Blocks
fieldLayouts:
  9c5a0f73-a60b-40b8-b730-94edc40cae4b:
    tabs:
      -
        elements:
          -
            fieldUid: 5c20a627-5111-454c-af25-51dd24681d70 # Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 043dff96-faf7-47d4-a319-43ad57ccfec5 # Hash Tag
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Main
        sortOrder: 1
group: null
handle: instagram
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: Instagram
topLevel: true
