childBlocks: null
conditions: null
description: ''
enabled: true
field: 33e21064-b628-40c7-b468-ea1796d59834 # Blocks
fieldLayouts:
  82ba5c9a-e22b-49b4-a4e8-0f32cdaaf4a0:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 4095fa84-00a3-4d80-af89-4b51ebedf570 # CTA Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5f071fbb-4fa4-4735-b3bc-19f806483f9d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 48539df8-1a5c-4798-ac79-aaa892721dac # CTA Link Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d5a4ba95-1e4f-42a7-b9cf-f8492f15f85d
            userCondition: null
            warning: null
            width: 100
        name: Main
        uid: b8706d31-5b71-49aa-9807-8a4b500cb3c5
        userCondition: null
group: null
groupChildBlockTypes: true
handle: link
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: Link
topLevel: false
