childBlocks:
  - pathway
conditions: null
description: ''
enabled: true
field: 33e21064-b628-40c7-b468-ea1796d59834 # Blocks
fieldLayouts:
  4f347822-4b09-4092-a2a9-aa92f564f99f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 5c20a627-5111-454c-af25-51dd24681d70 # Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 65ba6924-b5f6-4da0-b26e-f2b847574ca5
            userCondition: null
            warning: null
            width: 100
        name: Main
        uid: 6bd3bca9-23be-40db-91ef-4b1dfccb0d2e
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 477046a3-12f5-4a73-82c4-d7e4fc8f9958 # Bottom Spacing
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f4ebf478-21b2-49dc-9639-0f130b844d3b
            userCondition: null
            warning: null
            width: 100
        name: Spacing
        uid: d0aedb5a-62db-41fb-b138-c77a51bf2583
        userCondition: null
group: null
groupChildBlockTypes: true
handle: pathways
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: Pathways
topLevel: true
