childBlocks: null
field: 33e21064-b628-40c7-b468-ea1796d59834 # Blocks
fieldLayouts:
  e060ced9-f8f9-4483-a625-58f80147798d:
    tabs:
      -
        elements:
          -
            fieldUid: 5c20a627-5111-454c-af25-51dd24681d70 # Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 1daac8ae-48ce-4136-8e38-11d6885fdf55 # People
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Main
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 477046a3-12f5-4a73-82c4-d7e4fc8f9958 # Bottom Spacing
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Spacing
        sortOrder: 2
group: null
handle: peopleBlock
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: 'People Block'
topLevel: true
