childBlocks:
  - tab
field: 33e21064-b628-40c7-b468-ea1796d59834 # Blocks
fieldLayouts:
  bab67748-8af9-46ec-a834-c5d52ab655e4:
    tabs:
      -
        elements:
          -
            fieldUid: 477046a3-12f5-4a73-82c4-d7e4fc8f9958 # Bottom Spacing
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Spacing
        sortOrder: 1
group: null
handle: tabs
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: 'Tabs '
topLevel: true
