childBlocks:
  - tab
conditions: null
description: ''
enabled: true
field: 33e21064-b628-40c7-b468-ea1796d59834 # Blocks
fieldLayouts:
  bab67748-8af9-46ec-a834-c5d52ab655e4:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 477046a3-12f5-4a73-82c4-d7e4fc8f9958 # Bottom Spacing
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 007c7694-7138-48cf-95b0-d804e5715a70
            userCondition: null
            warning: null
            width: 100
        name: Spacing
        uid: a8c9b5cf-c120-4923-94e0-e5f68bead49b
        userCondition: null
group: null
groupChildBlockTypes: true
handle: tabs
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Tabs '
topLevel: true
