childBlocks:
  - column
conditions: null
description: ''
enabled: true
field: 33e21064-b628-40c7-b468-ea1796d59834 # Blocks
fieldLayouts:
  7dcf23a4-273f-4772-a887-4ffb9cd56e71:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 5c20a627-5111-454c-af25-51dd24681d70 # Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5fde4271-f187-47c8-ad31-31370013abd9
            userCondition: null
            warning: null
            width: 100
        name: Main
        uid: 091e483d-be61-45ae-a2c5-13faec6b27bb
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 477046a3-12f5-4a73-82c4-d7e4fc8f9958 # Bottom Spacing
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6144ce6d-7028-4f0f-ba79-a6c5a0d39745
            userCondition: null
            warning: null
            width: 100
        name: Spacing
        uid: b2bcc85e-ad23-4633-9800-dcce4b2915f9
        userCondition: null
group: null
groupChildBlockTypes: true
handle: threeColumnBlock
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Three Column Block'
topLevel: true
