columnSuffix: lpwxxies
contentColumnType: text
fieldGroup: 119b767b-7327-4978-8a4b-d81bcecb92b3 # Blocks
handle: animationPrimaryText
instructions: ''
name: 'Animation Primary Text'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
