columnSuffix: null
contentColumnType: string
fieldGroup: 119b767b-7327-4978-8a4b-d81bcecb92b3 # Blocks
handle: blocks
instructions: ''
name: Blocks
searchable: false
settings:
  maxBlocks: ''
  maxLevels: ''
  maxTopBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
  wasModified: false
translationKeyFormat: null
translationMethod: site
type: benf\neo\Field
