columnSuffix: kxirgyyz
contentColumnType: string
fieldGroup: e185f77d-0122-4574-9d97-3f9e0dba1dc5 # Common
handle: email
instructions: ''
name: Email
searchable: false
settings:
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Email
