columnSuffix: null
contentColumnType: string
fieldGroup: e185f77d-0122-4574-9d97-3f9e0dba1dc5 # Common
handle: expertise
instructions: ''
name: Expertise
searchable: false
settings:
  allowLimit: false
  allowMultipleSources: false
  allowSelfRelations: false
  branchLimit: ''
  limit: null
  localizeRelations: false
  selectionLabel: ''
  showSiteMenu: false
  source: 'group:758bf1dc-17fb-4a7a-901d-75cbdcfcc21f' # Expertise
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Categories
