columnSuffix: null
contentColumnType: string
fieldGroup: e185f77d-0122-4574-9d97-3f9e0dba1dc5 # Common
handle: expertiseSelection
instructions: ''
name: Expertise
searchable: false
settings:
  contentTable: '{{%matrixcontent_expertiseselection}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
