columnSuffix: fxzqarch
contentColumnType: text
fieldGroup: e185f77d-0122-4574-9d97-3f9e0dba1dc5 # Common
handle: getDirectionsLink
instructions: ''
name: 'Get Directions Link'
searchable: false
settings:
  allowCustomText: '1'
  allowTarget: ''
  allowedLinkNames:
    3: entry
    9: url
  autoNoReferrer: ''
  defaultLinkName: asset
  defaultText: ''
  enableAriaLabel: ''
  enableTitle: ''
  typeSettings:
    __assoc__:
      -
        - asset
        -
          __assoc__:
            -
              - sources
              - '*'
            -
              - allowCustomQuery
              - ''
      -
        - category
        -
          __assoc__:
            -
              - sources
              - '*'
            -
              - allowCustomQuery
              - ''
      -
        - entry
        -
          __assoc__:
            -
              - sources
              - '*'
            -
              - allowCustomQuery
              - ''
      -
        - site
        -
          __assoc__:
            -
              - sites
              - '*'
      -
        - user
        -
          __assoc__:
            -
              - sources
              - '*'
            -
              - allowCustomQuery
              - ''
      -
        - custom
        -
          __assoc__:
            -
              - disableValidation
              - ''
            -
              - allowAliases
              - ''
      -
        - email
        -
          __assoc__:
            -
              - disableValidation
              - ''
            -
              - allowAliases
              - ''
      -
        - tel
        -
          __assoc__:
            -
              - disableValidation
              - ''
            -
              - allowAliases
              - ''
      -
        - url
        -
          __assoc__:
            -
              - disableValidation
              - ''
            -
              - allowAliases
              - ''
translationKeyFormat: null
translationMethod: none
type: typedlinkfield\fields\LinkField
