columnSuffix: lzgiktpl
contentColumnType: text
fieldGroup: e185f77d-0122-4574-9d97-3f9e0dba1dc5 # Common
handle: hashTag
instructions: ''
name: 'Hash Tag'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
