columnSuffix: null
contentColumnType: string
fieldGroup: 87e8b875-aeb9-4fc8-b5ad-f1bf550e17b5 # Hero
handle: heroImage
instructions: ''
name: Image
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:1a6175db-796e-40fe-8912-5712ece9b34a' # Assets
  defaultUploadLocationSubpath: hero
  limit: '1'
  localizeRelations: false
  previewMode: full
  restrictFiles: '1'
  selectionLabel: ''
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:1a6175db-796e-40fe-8912-5712ece9b34a' # Assets
  singleUploadLocationSubpath: ''
  source: null
  sources: '*'
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
