columnSuffix: iabglrpb
contentColumnType: text
fieldGroup: 87e8b875-aeb9-4fc8-b5ad-f1bf550e17b5 # Hero
handle: heroTitle
instructions: ''
name: Title
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: '1'
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
