columnSuffix: cnikdyte
contentColumnType: boolean
fieldGroup: 119b767b-7327-4978-8a4b-d81bcecb92b3 # Blocks
handle: isInsightArticle
instructions: null
name: 'Is Insight Article?'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
