columnSuffix: hftukidm
contentColumnType: boolean
fieldGroup: 119b767b-7327-4978-8a4b-d81bcecb92b3 # Blocks
handle: isNewsArticle
instructions: null
name: 'Is News Article'
searchable: false
settings:
  default: true
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
