columnSuffix: etqjurxw
contentColumnType: string(255)
fieldGroup: e185f77d-0122-4574-9d97-3f9e0dba1dc5 # Common
handle: linkedin
instructions: ''
name: LinkedIn
searchable: false
settings:
  maxLength: '255'
  placeholder: null
  types:
    - url
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
