columnSuffix: null
contentColumnType: string
fieldGroup: e185f77d-0122-4574-9d97-3f9e0dba1dc5 # Common
handle: location
instructions: ''
name: Location
searchable: false
settings:
  allowSelfRelations: false
  limit: ''
  localizeRelations: false
  selectionLabel: ''
  showSiteMenu: true
  source: null
  sources:
    - 'section:58c93d6c-fb19-41d3-af7b-303681c35b56' # Location
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
