columnSuffix: kvngjzid
contentColumnType: string
fieldGroup: 119b767b-7327-4978-8a4b-d81bcecb92b3 # Blocks
handle: primaryImage
instructions: ''
name: Image
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:1a6175db-796e-40fe-8912-5712ece9b34a' # Assets
  defaultUploadLocationSubpath: blocks
  limit: '1'
  localizeRelations: false
  previewMode: full
  restrictFiles: '1'
  selectionLabel: ''
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:1a6175db-796e-40fe-8912-5712ece9b34a' # Assets
  singleUploadLocationSubpath: ''
  source: null
  sources: '*'
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
