columnSuffix: rlkwuhfk
contentColumnType: string
fieldGroup: 119b767b-7327-4978-8a4b-d81bcecb92b3 # Blocks
handle: sectionBottomSpacing
instructions: ''
name: 'Bottom Spacing'
searchable: false
settings:
  optgroups: true
  options:
    -
      __assoc__:
        -
          - label
          - None
        -
          - value
          - none
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Small
        -
          - value
          - sml
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Medium
        -
          - value
          - med
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Large
        -
          - value
          - lg
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
