columnSuffix: lcwhffya
contentColumnType: text
fieldGroup: 119b767b-7327-4978-8a4b-d81bcecb92b3 # Blocks
handle: sectionQuote
instructions: ''
name: Quote
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: '1'
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
