columnSuffix: svjrrrte
contentColumnType: string
fieldGroup: 119b767b-7327-4978-8a4b-d81bcecb92b3 # Blocks
handle: size
instructions: ''
name: Size
searchable: false
settings:
  optgroups: true
  options:
    -
      __assoc__:
        -
          - label
          - Small
        -
          - value
          - small
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Large
        -
          - value
          - large
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
