defaultPlacement: end
enableVersioning: true
handle: location
name: Location
propagationMethod: all
siteSettings:
  b435198f-89d2-4c06-b0e1-e3d2dc874d2c: # Tavendale & Partners
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
