defaultPlacement: end
enableVersioning: true
handle: newInsights
name: 'New & Insights'
propagationMethod: all
siteSettings:
  b435198f-89d2-4c06-b0e1-e3d2dc874d2c: # Tavendale & Partners
    enabledByDefault: true
    hasUrls: true
    template: _singles/news
    uriFormat: news
type: single
