defaultPlacement: end
enableVersioning: true
handle: newsPage
name: 'News Page'
propagationMethod: all
siteSettings:
  b435198f-89d2-4c06-b0e1-e3d2dc874d2c: # Tavendale & Partners
    enabledByDefault: true
    hasUrls: true
    template: _sections/page
    uriFormat: 'news/{slug}'
type: channel
