defaultPlacement: end
enableVersioning: true
handle: page
name: Page
propagationMethod: all
siteSettings:
  b435198f-89d2-4c06-b0e1-e3d2dc874d2c: # Tavendale & Partners
    enabledByDefault: true
    hasUrls: true
    template: _sections/page
    uriFormat: '{parent.uri}/{slug}'
structure:
  maxLevels: null
  uid: 7c956874-c226-42d0-9278-17b7df870590
type: structure
