defaultPlacement: end
enableVersioning: true
handle: people
name: People
propagationMethod: all
siteSettings:
  b435198f-89d2-4c06-b0e1-e3d2dc874d2c: # Tavendale & Partners
    enabledByDefault: true
    hasUrls: true
    template: _channels/person
    uriFormat: 'our-people/{slug}'
type: channel
